language: node_js
sudo: required
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '10'
install:
- npm ci
script:
- npm run travis:verify
after_success:
- ls
- cd dist/
- git init
- git remote add test-build https://ryelo:${GH_TOKEN}@github.com/ryelo/build.git > /dev/null 2>&1
- git add .
- git commit -m 'travis build'
- git push -f --quiet --set-upstream test-build master
env:
  global:
    secure: svTWhgSo/4tFWF/h7K5HqRAf2vALTYODSWn0MSEEQrMErMXccQBo6O2fYnvcPg2hHtsIK5zrvugyF2wROveNkjbHWN+258AQBZtceBgYGc6NmVDwojwoMyXSKbFOliy4MfIM01aOxPp2nbULy/bTRcnVdmQg9NsvKgzoLVtxxuPN9x5TFvxPnQtjWpRVMRNiFEIZ9hzZ+x9S4yRcY2mqPaUMpCrHuXTCKgXh1TaJKXhADhT6jCY2mIEvJwTmdSClZSaXaOc1/DN5Ik3pCjJ7NqKJ0tw0rTvavTAgOq3rT2ryRvhsqYEoDvmA7Z8mJiIuTYw46++Iq6IiQJDCtGz/6Lgqkr51fsIBEWvQB4icsFNqzytbbMHKfRbIXuGGfg5tWFdHO4TA+tOJ2w8SxyziJ1/ZSNCdo8w0SnBumLYkTS52e+/xFVYu+OfRABAebd2x1HUJArAOnHwLT3MMixfwja47avzB6+Grp3IRS4YJT9bcEOWn73fickmXUtHmdcR4uxAWNAOJxCr/8cthAIEUyyCqoNcWuDHNbdzApvN1jKRlF2SCPZJZ44JFGcq1NBnsyXQLaa8yHffSwNCnlVJs5x62WTgBn82mfZ54fQZW86qy98MrWaceGCjZ3gAg7Dp9n/uWhQJMWQHd+UYCmzXDfxU0byaA1vtQOg5FZenqbjw=
RedHatInsights:
  secure: RPRrlEwW4xm3WEP0nKJrNHTLoJqVQ6zic9rseees/AJVGJWhD25KvBTamR66uJYUttbI1LDrLpXf5yN+/ElgcuKNY3/fU5dfpTZlgC5uVnCxkHswrJagjW/Z6TEBU8ysrhkAwpULRnfK7Dzj0Z5dpzoxKRdWGMbheF4BPmvluPXZYkhXb1fV9dZkZU1+unsBcUIWwPPzBNr/t+tEdyW67fstdgNzUs9EPiwfN6Q97TXgbby47KFVkAVB0vZBj/tdO9aePVHRxHjKkTroWG4mqdRhdmXydnivvCBHCny3HYoH0InhpvWiKulkOHgM29r/Xm+SOz+BWnn+JTGJytlp6idJBUKknSouxyKsUaba4RLcJE+PQoEJ2/ZB7hhb0J+/sokk7Km2U9zT2NpCUjMHh1L//8NLgKx21d5SpxCsTkv6/H93U/0lCbQlkzbiu3rxw6lnNZ/LwVTcZQf5ApKRm3S8/7TDtzHuWyRhsR6KMfqKb9xqmkF7ZDuLpD5v7QfHtBDzgj22Uy64LbR++xc4+rwGrgGUOO6ipjPAINTO94C+70sruM8phvhXD52gKO6XARFQprNIqBwCgPwR7R8RaTgwyT5QVup/uoNVTNP5GHEvJsCgj7RVoGFNve5lkZoNa0XwupE9nbNo3dOeZhEY8JTsG1PiRpifk6UTmUcJ6LI=