language: node_js
sudo: required
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '10'
install:
- npm ci
script:
- npm run travis:verify
after_success:
- .travis/after_success.sh
env:
  global:
  - REPO="git@github.com:RedHatInsights/insights-deployment-test-build"
  - FILES="dist/index.html"
  - GH_REPO="https://github.com/RedHatInsights/insights-deployment-test"
