language: node_js
sudo: required
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '10'
install:
- npm ci
script:
- npm run travis:verify
before_install:
- openssl aes-256-cbc -K $encrypted_2eeb7a4fa1ff_key -iv $encrypted_2eeb7a4fa1ff_iv -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- ssh-add deploy_key
env:
  global:
  - REPO="git@github.com:RedHatInsights/insights-deployment-test-build"
  - FILES="dist/index.html"
  - GH_REPO="https://github.com/RedHatInsights/insights-deployment-test"
after_success:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- cd dist
- git init
- git config --global user.name "Kinlaw"
- git config --global user.email jkinlaw@redhat.com
- git remote add build_Kinlaw git@github.com:${REPO}.git
- git add .
- git commit -m 'travis commit'
- git config --list
- git push --force --set-upstream build_Kinlaw master
