language: node_js
sudo: required
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '10'
install:
- npm ci
script:
- npm run travis:verify
- .travis/test.sh
before_install:
- openssl aes-256-cbc -K $encrypted_2eeb7a4fa1ff_key -iv $encrypted_2eeb7a4fa1ff_iv -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key
after_success:
- .travis/after_success.sh
env:
  global:
  - REPO="git@github.com:RedHatInsights/insights-deployment-test-build"
  - FILES="dist/index.html"
  - GH_REPO="https://github.com/RedHatInsights/insights-deployment-test"
